### ISSUE TITLE
 Listado de necesidades del  backend con respecto al front  para app móvil

### ISSUE THREAD

**Issue by CARPER11** [Azordev/did-app#53]
Plantilla.
**Explicación:**
El listado de necesidades del front con respecto al backend par app movil, es una tarea para ser realizada por  @CARPER11 con la finalidad de cubrir las necesidades que tenemos en el front con respecto a los datos que debe proporcionar la base de datos y el backend..

**Criterios de aceptación:**
- [ ] Se creó y  envió la lista de necesidades para #13 
- [ ] Se creó y  envió la lista de necesidades para #14 
- [ ] Se creó y  envió la lista de necesidades para #17  
- [ ] Se creó y  envió la lista de necesidades para #18 
- [ ] Se creó y  envió la lista de necesidades para #19 
- [ ] Se creó y  envió la lista de necesidades para #3 
- [ ] Se creó y  envió la lista de necesidades para #4 
- [ ] Se creó y  envió la lista de necesidades para #6 
- [ ] Se creó y  envió la lista de necesidades para #7 
- [ ] Se creó y  envió la lista de necesidades para #12  
- [ ] Se creó y  envió la lista de necesidades para #15 
- [ ] Se creó y  envió la lista de necesidades para #16 
- [ ] Se creó y  envió la lista de necesidades para #20 
- [ ] Se creó y  envió la lista de necesidades para #21
- [ ] Se creó y  envió la lista de necesidades para #22 
- [ ] Se creó y  envió la lista de necesidades para #24 
- [ ] Se creó y  envió la lista de necesidades para #25  
- [ ] Se creó y  envió la lista de necesidades para #26 
- [ ] Se creó y  envió la lista de necesidades para #27
- [ ] Se creó y  envió la lista de necesidades para #28  
- [ ] Se creó y  envió la lista de necesidades para  #32
