### ISSUE TITLE
Front To Backend Needs List For Mobile App  /  Lista De Necesidades Del Front Respecto Al Backend Para La Aplicación Móvil

### ISSUE THREAD

**Issue by CARPER11** [Azordev/did-app#54]
Template

**Explanation:**

The list of needs of the Front regarding the Backend for the Mobile App, is a task to be carried out by @CARPER11 in order to cover the needs that we have in the Front regarding the data that the Database and the Backend must provide. ..

**Criteria of acceptance:**

- [ ] The list of needs for #13 was created and sent
- [ ] The list of needs for #14 was created and sent
- [ ] The list of needs for #17 was created and sent
- [ ] The list of needs for #18 was created and sent
- [ ] The list of needs for #19 was created and sent
- [ ] The list of needs for #3 was created and sent
- [ ] The list of needs for #4 was created and sent
- [ ] The list of needs for #6 was created and sent
- [ ] The list of needs for #7 was created and sent
- [ ] The list of needs for #12 was created and sent
- [ ] The list of needs for #15 was created and sent
- [ ] The list of needs for #16 was created and sent
- [ ] The list of needs for #20 was created and sent
- [ ] The list of needs for #21 was created and sent
- [ ] The list of needs for #22 was created and sent
- [ ] The list of needs for #24 was created and sent
- [ ] The list of needs for #25 was created and sent
- [ ] The list of needs for #26 was created and sent
- [ ] The list of needs for #27 was created and sent
- [ ] The list of needs for #28 was created and sent
- [ ] The list of needs for #32 was created and sent

---

# Spanish Version

Plantilla

**Explicación:**

El listado de necesidades del Front con respecto al Backend para App Móvil, es una tarea para ser realizada por  @CARPER11 con la finalidad de cubrir las necesidades que tenemos en el Front con respecto a los datos que debe proporcionar la "Base de Datos y el Backend".

**Criterios de aceptación:**

- [ ] Se creó y  envió la lista de necesidades para #13 
- [ ] Se creó y  envió la lista de necesidades para #14 
- [ ] Se creó y  envió la lista de necesidades para #17  
- [ ] Se creó y  envió la lista de necesidades para #18 
- [ ] Se creó y  envió la lista de necesidades para #19 
- [ ] Se creó y  envió la lista de necesidades para #3 
- [ ] Se creó y  envió la lista de necesidades para #4 
- [ ] Se creó y  envió la lista de necesidades para #6 
- [ ] Se creó y  envió la lista de necesidades para #7 
- [ ] Se creó y  envió la lista de necesidades para #12  
- [ ] Se creó y  envió la lista de necesidades para #15 
- [ ] Se creó y  envió la lista de necesidades para #16 
- [ ] Se creó y  envió la lista de necesidades para #20 
- [ ] Se creó y  envió la lista de necesidades para #21
- [ ] Se creó y  envió la lista de necesidades para #22 
- [ ] Se creó y  envió la lista de necesidades para #24 
- [ ] Se creó y  envió la lista de necesidades para #25  
- [ ] Se creó y  envió la lista de necesidades para #26 
- [ ] Se creó y  envió la lista de necesidades para #27
- [ ] Se creó y  envió la lista de necesidades para #28  
- [ ] Se creó y  envió la lista de necesidades para  #32
